go:
	go vet          ./...
	go test -cover  ./...
	go build        ./...

coverage:
	go test -coverprofile=cov ./...
	go tool cover -html=cov

benchmark:
	go test -bench=. -benchmem .

.PHONY: go coverage benchmark
