go:
	go fmt		./...
	go tool vet -composites=false .
	go build	./...
	go test -cover	./...
	go install		./...

cover:
	go test -coverprofile=cov
	go tool cover -html=cov

benchmark:
	go test -bench=. -benchmem .
