go:
	go fmt          ./...
	go build        ./...
	go test -cover  ./...
	go install      ./...

coverage:
	go test -coverprofile=cov
	go tool cover -html=cov

benchmark:
	go test -bench=. -benchmem .
